### ISSUE TITLE
Update cheat mode/debugging mode steamids

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/custom_hero_chaos_2#4]
Game is currently hardcoded to allow two users to have debug/cheat mode, we should update this to include Firetoad, @Sheodar, @SanctusAnimus and myself. 

https://github.com/darklordabc/custom_hero_chaos_2/blob/aa01da3be31a662bec74213404d5ad3e22326a36/game/scripts/vscripts/debugger.lua#L19

**Comment by darklordabc** [comment]
My profile is https://steamcommunity.com/profiles/76561198054179075/

**Comment by fcalife** [comment]
Here's mine https://steamcommunity.com/id/fcalife/

**Comment by SanctusAnimus** [comment]
Updated in commit 97aad73, closing for now
